### ISSUE TITLE
reactive => toRef => reactive chain leads to dev tools incorrectly saying ref value is undefined

### ISSUE THREAD

**Issue by henribru** [vuejs/devtools-v6#2105]
### Vue devtools version

6.5.0

### Link to minimal reproduction

https://play.vuejs.org/#eNp9kjFPwzAQhf/KyQupFKWVKpbSVgLUAQZApaOXkF6KS2JbtlOqRv7vnB2SFgl1Svzue3fvErfsXuvs0CCbsbktjNAOLLpGL7kUtVbGQQsG88KJA6bg1BpL8FAaVcMN2W645LJQ0joolYLFwCZtEGbAGT04Az+668GP3BAYWyVUTHvmkjj9bRUssQNl24gaVeOSZASLJbRcQpiUdeM5I5QzIn0Kt5PJJJjm424z2okODmtd5Q7pBNDGmNHs/a8Qh50Pp6wX5uPBy1LmLIUtxS7bWyXp88UknBWq1qJC86qdoGU4m3UZQy2vKvX9HDVnGkx7vfjE4usffW+PQePszaBFc0DOhprLzQ5dV169v+CR3odirbZNRfSV4hqtqpqQscMeGrml2BdcTPsUL4GQu41dHR1K2y8VggbSR54zugyPV1Y/x51m0+ijX8T8D/VF0/g=

### Steps to reproduce & screenshots

Observe the state of `foo`, `bar` and `baz` in the devtools. `foo.foo` will initially have the value `"foo"` and so will `bar.value`, but `baz.bar` will show as `undefined`, despite the fact that in the template they all show as `"foo"`. After 5 seconds, we change the value to `"bar"`, and this is reflected in the template and in the devtools for `foo` and `bar`, but `baz.bar` is still shown as `undefined`.

![image](https://github.com/vuejs/devtools/assets/6639509/2a0082c9-057a-4f89-b2de-131e7ad0a701)

![image](https://github.com/vuejs/devtools/assets/6639509/a3610edb-c218-489b-9cd9-06ad334615e7)

### What is expected?

`foo.foo`, `bar.value` and `baz.bar` should all show as `"foo"` at first and then `"bar"`

### What is actually happening?

`baz.bar` is shown as `undefined` both before and after the change.

### System Info

```shell
System:
    OS: Linux 6.2 Ubuntu 23.04 23.04 (Lunar Lobster)
    CPU: (8) x64 Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
    Memory: 9.27 GB / 31.24 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 18.17.1 - ~/.asdf/installs/nodejs/18.17.1/bin/node
    npm: 9.6.7 - ~/.asdf/plugins/nodejs/shims/npm
    Watchman: 4.9.0 - /usr/bin/watchman
  Browsers:
    Chromium: 116.0.5845.187
  npmPackages:
    vue: ^3.3.4 => 3.3.4
```

**Comment by voxivoid** [comment]
hello 👋

I think I'm also facing this issue. I managed to reproduce it with the following [code](https://play.vuejs.org/#__DEV__eNp9U01vm0AQ/SujvRhLyFaVm4WR2iiHtFKbJjnuhcLg4MIu2l0cWy7/vcN+AI6tSLDSzud782bP7Gvbrg4dsg1LdK6q1qRcVE0rlYEzdBpfUZt7KQweDfRQKtnAYrW+dCy4wKNNKbDMuppSuQDQaLo2WroLQC6FJk+RmayH7Yfa0ZILF6YoSwkfN5jooI+LZD0CpIvBpq0zg3QDSN6+pOczDCnQ98markP8GMNiZjT1L6vdaq+lILYWFGe5bNqqRvWrNRXh42wT4HKW1bV8/25tRnUYB3v+hvnfG/a9Pg42zp4UalQH5Gz0mUzt0Dj3w8tPYjxzNrLoaor+xPmMWtbdgNGFfetEQbBncRbto1WuErtX/XA0KHQgNQC1w7TxnJHk959Qn+Dere6CCDRFL9rvDtVpZTTNMeyKwjIGI5+x1DFpmOWmOmBYGOq24Ip0o99vituGeT3aCVqWbUooKCzsi9V0SxXLRBtFzFJaFV8KQOA7PFGLSmN0kQw2cXXI6g4pnRhRG86cs59V8OvmkEcBeBSWaWlD++GY6PudvRxAq+ShKjAGKhTDo9gjVZLiB54+TiFkzMn7GM7Gt2XNDnH4zalFCI9xG6gOQDdDVz8g+Ae0HFhWAot0RD/8bqIzBi+n5o+sNxdoE+9LqYPzR5zNcjgbp3dLygneDTHDVKfnb1nOFXWBdA5VNtdsHd/YCznl+fFHV+ziUOxadO+YFO7/A5Xbw9M=)


![image](https://github.com/vuejs/devtools/assets/7469472/2ef07b18-15b3-479c-b66c-7117a89b0694)

**Comment by kien-ht** [comment]
any update on this? I have encountered the same problem

**Comment by partyk** [comment]
I have the same problem and here is the code to simulate it. [Link code](https://play.vuejs.org/#eNqtVE2P2jAQ/SuWL4BAgSQ9QUBt0R7aQ7vatrdIVRomNLuOHfmDIqH8947tBMLyUbXqIbIz82beeDzPB/quroOdATqnicplWWuiQJt6lfKyqoXU5EAkFKQhhRQVGSB0cHQRo2AtDNcgW3cwPZkGi5SnPBdcaZK3qGUvZDjqAQT/Vm8yDYgYjshyRQ4pJ11Y4NYw2GXMWMRV85iEM0zYHJMKBgET22GLtmzJ1J8RT4c/GqqaISf+EZIY5lbcsXJ1OJxzNE0yRfNNQPQnQNwDJNOWK/lhtBacvM1Zmb8sU9qFlDyXUAHXrlXhcJTS1dpi/NFJmEx96PU0XTMv48g4nN2PvV5CdJEq+pc08UWauJcmmfZuhE6oVniNRbkNnpXgOKBuJGzqqi4ZyM+1LvGaUzr3w2J9GWPi10dn09LApLPnPyF/uWJ/VntrS+mjBAVyByk9+nQmt6C9++HLJ9jj/uisxMYwRN9xPgGOoLE1eth7wzdYdg/nqv3gtFTy7Vf1sNfAVXcoW6hFNg6fUpTe+s7RT+XGwRsXh2LALp4Eh33ELvZkneW63MGEaPEEheo07phSukglqgQ/2LuADRSZYZoUhmMY3jUmfsy2Jc+0QC1jIYi1krVyVtprueMYtt5W0uGczCZnlmiO8j03xXMSdaYG1duW01G80kjv4WiTuBpa/Y7HLt7nPj0NfYhnQKp2vcYS3WWJ/hNLfJcl/msWv5f4rEt+ShkEgb93Hzk6Nv9VY2/Yoxv2uLsxuzQLHMDvO5B2qHH2cDKDOKbNb4t7L3Y=)

**App.vue**

`<script setup>
import { ref } from 'vue'
import  useCounter from './useCounter';

const counter = useCounter();

const onUpdate = () => {
  counter.count1.value = counter.count1.value + 10;
};

console.log(counter);
</script>

<template>
  <ul>
    <li>{{counter.count1}}</li>
    <li>{{counter.count2}}</li>
    <li>{{counter.count3}}</li>
  </ul>
  <button @click="counter.incrementCount1()">Click count 1</button>
  <button @click="onUpdate()">Click count 1 +10</button>
  <button @click="counter.incrementCount2()">Click count 2</button>
  <button @click="counter.incrementCount3()">Click count 3</button>
</template>
`

**useCounter.js**

`
import { reactive, toRefs } from "vue";

export default function usePaginator() {
  const state = reactive({
    count1: 0,
    count2: 10,
    count3: 20,
  });

  const incrementCount1 = () => {
    state.count1++;
    console.log(state.count1);
  };
  const incrementCount2 = () => {
    state.count2++;
    console.log(state.count1);
  };
  const incrementCount3 = () => {
    state.count3++;
    console.log(state.count1);
  };

  return {
    ...toRefs(state),
    incrementCount1,
    incrementCount2,
    incrementCount3,
  }
};
`

**Comment by henribru** [comment]
Seems like this was a bug in Vue, as it works fine with Vue 3.5. No idea which commit fixed it.
